#ifndef SUBMODULES_LIBCRYPTO_INCLUDE_HASH_TYPES_H_
#define SUBMODULES_LIBCRYPTO_INCLUDE_HASH_TYPES_H_

#define x86_CORE

enum class Hash_Result{
	ERROR_INIT, SUCCES_INIT,
	ERROR_UPDATE, SUCCES_UPDATE,
	ERROR_FINAL, SUCCES_FINAL,
	ERROR_HASH, SUCCES_HASH};


#endif /* SUBMODULES_LIBCRYPTO_INCLUDE_HASH_TYPES_H_ */
